# Site settings
name: 小乌龟 の blog
title: iPython
email: xiaowugui244345021@163.com
description: "Python技术、gevent高并发库以及生活随记"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalinks: pretty
